services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=messaging_app.settings
    command: python messaging_app/manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
