apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  selector:
    app: messaging-app
    version: blue # switch this to 'green' when ready
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
